### ISSUE TITLE
Creating a project with two scenarios connected by button press

### ISSUE THREAD

**Issue by DSantaguida** [SanjayP9/EECS-2311-TBB_Project#2]
OS: Windows 10
Java Version: 8
Description: Gives an error when building a project with two events, where the first even connects to the second event through a button press.
Steps to reproduce: Open the app, Create a new scenario, add two events, on the first even choose to go to the next even through a button press, build project, errors will appear on screen.
Expected: Scenario to be created without any issues.
Actual: Multiple error messages appear on screen.

**Comment by DamanB** [comment]
HI, I looked into the problem you were experiencing and fixed it for the next release. Thanks!
