### ISSUE TITLE
Not displaying pin 1 on first braille cell from created scenario file

### ISSUE THREAD

**Issue by sohnsteve** [SanjayP9/EECS-2311-TBB_Project#3]
OS: macOS (High Sierra) v. 10.13.3
Java version: Java 8

Description of bug:
This bug arises when creating a scenario file using the create scenario editor.  When creating the scenario event that displays a particular pin, the selected pin will not show upon running the scenario.

Expected:
We selected the top-left pin to be highlighted.  When running the scenario, the top-left pin should be displayed/highlighted in some way.

Actual:
When running the scenario, the top-left pin is not highlighted, a blank Braille cell is shown.

Steps to reproduce:
1. Create a scenario file.
2. Number of braille cells selected: 2.  Number of response buttons: 2.
3. Event was named "pageone".
4. In drop-down menu, selected "Display Pins on Braille Cell".
5. In configuration, Braille Cell: 1 selected, and top-left pin selected.
6. Save scenario file by selecting Build Project!
7. Run saved scenario.  Upon loading, the top-left pin is not highlighted.

Attached are screen shots of the pin selection and the scenario being run.
<img width="1117" alt="screen shot 2018-03-06 at 12 51 01 pm" src="https://user-images.githubusercontent.com/35306671/37049049-adfa0f46-213d-11e8-8580-f7f729282847.png">
<img width="660" alt="screen shot 2018-03-06 at 12 49 45 pm" src="https://user-images.githubusercontent.com/35306671/37049052-b08d6b18-213d-11e8-9116-50878af6abc0.png">

**Comment by SanjayP9** [comment]
I also noticed that this bug also exists for the professors original version of the project. I will contact him about it. Thanks.

**Comment by DamanB** [comment]
Hi,
We have currently looked into this bug and fixed the issue in our newest release. Recreating this event now displays the correct pin on the top left.

Thanks!
